//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESBPublic.Model
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ESBPublicEntities : DbContext
    {
        public ESBPublicEntities()
            : base("name=ESBPublicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lookup_Language> Lookup_Language { get; set; }
        public virtual DbSet<Lookup_Projects> Lookup_Projects { get; set; }
        public virtual DbSet<Table_WebMessages> Table_WebMessages { get; set; }
    }
}
