//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;
using System.Linq;

namespace MOL.EFDAL.Repository
{
    public partial class CJD_Online_Requests_Repository : EFRepository<CJD_Online_Requests>
    {
        public CJD_Online_Requests_Repository()
        {
            Context = new MOLEFEntities();
        }

        public CJD_Online_Requests_Repository(MOLEFEntities context) : base(context)
        {

        }

        public double? GetRequesterIdNumber(int laborOfficeId, int serialYear, int serialNumber, Mol.Entities.ServiceList serviceId)
        {
            return this.SingleOrDefault(cjd =>
                        cjd.MOL_OracleTransactionLog.Any(o => o.Lab_Off == laborOfficeId
                                && o.Ser_YY == serialYear
                                && o.Seq_No == serialNumber
                                && o.FK_ServiceId == (int)serviceId))?.MOL_User?.Id_Number;
        }
    }
}

