//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;

namespace MOL.EFDAL.Repository
{
    public partial class CLB_Online_Requests_Repository : EFRepository<CLB_Online_Requests>
    {
        public CLB_Online_Requests_Repository()
        {
            Context = new MOLEFEntities();
        }

        public CLB_Online_Requests_Repository(MOLEFEntities context) : base(context)
        {

        }
    }
}

