//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;

namespace MOL.EFDAL.Repository
{
    public partial class IST_Online_Appoval_Repository : EFRepository<IST_Online_Appoval>
    {
        public IST_Online_Appoval_Repository()
        {
            Context = new MOLEFEntities();
        }

        public IST_Online_Appoval_Repository(MOLEFEntities context) : base(context)
        {

        }
    }
}

