//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;

namespace MOL.EFDAL.Repository
{
    public partial class Joining_Rule_Repository : EFRepository<Joining_Rule>
    {
        public Joining_Rule_Repository()
        {

        }

        public Joining_Rule_Repository(MOLEFEntities context) : base(context)
        {

        }
    }
}

