//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;

namespace MOL.EFDAL.Repository
{
    public partial class MOL_Download_Repository : EFRepository<MOL_Download>
    {
        public MOL_Download_Repository()
        {
           
        }

        public MOL_Download_Repository(MOLEFEntities context) : base(context)
        {

        }
    }
}

