//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;
using System.Collections.Generic;
using System.Linq;

namespace MOL.EFDAL.Repository
{
    public partial class MOL_IssuedVisas_Repository : EFRepository<MOL_IssuedVisas>
    {
        public MOL_IssuedVisas_Repository()
        {
            Context = new MOLEFEntities();
        }

        public MOL_IssuedVisas_Repository(MOLEFEntities context) : base(context)
        {

        }

        public List<MOL_IssuedVisas> GetIssuedVisasPendingRefund()
        {
            return (from p in Context.MOL_IssuedVisas

                    where p.CreditID.HasValue
                    && p.CreditType.HasValue
                    && (p.IsRefunded.HasValue == false || p.IsRefunded == false)
                    && p.VisaStatus == 2
                    select p).ToList();
        }
    }
}

