//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;
using System.Collections.Generic;
using System.Linq;

namespace MOL.EFDAL.Repository
{
    public partial class MOL_EstablishmentStatement_Repository : EFRepository<MOL_EstablishmentStatement>
    {
        public MOL_EstablishmentStatement_Repository()
        {
            Context = new MOLEFEntities();
        }

        public MOL_EstablishmentStatement_Repository(MOLEFEntities context) : base(context)
        {

        }
        public List<MOL_EstablishmentStatement> GetByStatementNumberAndType(string statementNumber,short TypeID)
        {
           return Context.MOL_EstablishmentStatement.Where(s => s.StatementNumber == statementNumber && s.FK_StatementTypeId == TypeID).ToList();
        }
    }
}

