//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;
using System.Linq;

namespace MOL.EFDAL.Repository
{
    public partial class MOL_WorkPermit_Repository : EFRepository<MOL_WorkPermit>
    {
        public MOL_WorkPermit_Repository()
        {
            Context = new MOLEFEntities();
        }

        public MOL_WorkPermit_Repository(MOLEFEntities context) : base(context)
        {

        }

        public void CancelFinalExitWorkPermit(MOL_CancelFinalExitWorkPermit cancelFinalExitWorkPermitLog)
        {
            UnitOfWork un = new UnitOfWork();

            var workPermit = un.MOL_WorkPermit_Repository.GetById(cancelFinalExitWorkPermitLog.CanceledWPId);

            workPermit.MOL_Srv_Transaction.FK_Service_LastServiceStatusId = 17;
            workPermit.MOL_Laborer.FK_WPId = cancelFinalExitWorkPermitLog.OldWPId;
            workPermit.MOL_Laborer.FK_LastWPId = cancelFinalExitWorkPermitLog.OldWPId;
            un.MOL_CancelFinalExitWorkPermit_Repository.Insert(cancelFinalExitWorkPermitLog);

            un.MOL_WorkPermit_Repository.Save();
        }

        public long? GetLastPaidWorkPermit(long laborerId)
        {
            long? wpId = (from w in Context.MOL_WorkPermit
                          join t in Context.MOL_Srv_Transaction on w.FK_Service_TransactionId equals t.PK_Service_TransactionId
                          where w.FK_LaborId == laborerId
                          && t.FK_Service_LastServiceStatusId == 3
                          && (w.FK_Servcie_ServiceRequestTypeId == 1 || w.FK_Servcie_ServiceRequestTypeId == 2)
                          orderby t.TransactionDate descending
                          select w.PK_WPId).Take(1).FirstOrDefault();

            return (wpId == 0 ? null : wpId);
        }
    }
}

