//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;

namespace MOL.EFDAL.Repository
{
    public partial class Mol_EstablishmentActivityCorrection_Repository : EFRepository<Mol_EstablishmentActivityCorrection>
    {
        public Mol_EstablishmentActivityCorrection_Repository()
        {
            Context = new MOLEFEntities();
        }

        public Mol_EstablishmentActivityCorrection_Repository(MOLEFEntities context) : base(context)
        {

        }
    }
}

