//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;
using System.Linq;

namespace MOL.EFDAL.Repository
{
    public partial class MOL_User_Repository : EFRepository<MOL_User>
    {
        public MOL_User_Repository()
        {
            Context = new MOLEFEntities();
        }

        public MOL_User_Repository(MOLEFEntities context) : base(context)
        {

        }

        public MOL_User GetUserByIdNoForEstablishmentSelect(long idNo)
        {
            var users = this.Where(w => w.Id_Number == idNo).ToList();
            if (users.Any())
            {
                if (users.Count() == 1)
                {
                    return users[0];
                }
                else
                {
                    var user = users.SingleOrDefault(w => w.UserName == idNo.ToString());
                    return user ?? users[0];
                }
            }

            return null;
        }

        public MOL_User GetUserByIdNoForIndividualSelect(long idNo)
        {
            return this.Where(u => u.Id_Number == idNo && u.IsUserDeleted != true && (u.User_Type_Id == 1 || u.User_Type_Id == 3)).FirstOrDefault();
        }

        public MOL_User GetUserByIdNo(long idNo)
        {
            return this.Where(user => user.Id_Number == idNo && (user.IsUserDeleted == null || user.IsUserDeleted == false)).FirstOrDefault();
        }
    }
}

