//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MOL.EFDAL.Models;

namespace MOL.EFDAL.Repository
{
    public partial class NitaqatActivity_Establishment_Repository : EFRepository<NitaqatActivity_Establishment>
    {
        public NitaqatActivity_Establishment_Repository()
        {

        }

        public NitaqatActivity_Establishment_Repository(MOLEFEntities context) : base(context)
        {

        }
    }
}

