//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Channels
    {
        public Channels()
        {
            this.MOL_GC_Assents = new HashSet<MOL_GC_Assents>();
            this.MOL_GC_Contracts = new HashSet<MOL_GC_Contracts>();
        }
    
        public long ID { get; set; }
        public long ChannelTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<long> PaymentMethodID { get; set; }
        public Nullable<long> PricePackageID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Attachment { get; set; }
        public string PrivilegesManagerIDNumber { get; set; }
        public Nullable<int> Gov_Agency_Id { get; set; }
    
        public virtual ICollection<MOL_GC_Assents> MOL_GC_Assents { get; set; }
        public virtual ICollection<MOL_GC_Contracts> MOL_GC_Contracts { get; set; }
        public virtual Gov_Agency Gov_Agency { get; set; }
    }
}
