//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Gov_Agency
    {
        public Gov_Agency()
        {
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Statistics_Report_Enabled { get; set; }
        public string Recipients { get; set; }
        public Nullable<int> Parent_Agency_Id { get; set; }

        public virtual ICollection<Channels> Channels { get; set; } = new HashSet<Channels>();
    }
}
