//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;

    public partial class Joining_Rule_Establishment_Type
    {
        public int Id { get; set; }
        public int Joining_Rule_Id { get; set; }
        public int Establishment_Type_Id { get; set; }
        public Nullable<bool> Block { get; set; }
    }
}
