//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System.Collections.Generic;

    public partial class Lookup_GC_ContractFields
    {
        public Lookup_GC_ContractFields()
        {
            this.MOL_GC_Contracts = new HashSet<MOL_GC_Contracts>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public double LaborCostRatio { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<MOL_GC_Contracts> MOL_GC_Contracts { get; set; }
    }
}
