//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MOL_EstablishmentVisaCreditJobs
    {
        public MOL_EstablishmentVisaCreditJobs()
        {
            this.MOL_EstablishmentVisaCreditJobsHistory = new HashSet<MOL_EstablishmentVisaCreditJobsHistory>();
        }
    
        public int ID { get; set; }
        public int VisaCreditID { get; set; }
        public int JobID { get; set; }
        public int GenderID { get; set; }
        public int ApprovedCredit { get; set; }
        public int UsedCredit { get; set; }
        public Nullable<int> AvailableCredit { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> LastModifiedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Enum_Gender Enum_Gender { get; set; }
        public virtual Lookup_Job Lookup_Job { get; set; }
        public virtual MOL_EstablishmentVisaCredit MOL_EstablishmentVisaCredit { get; set; }
        public virtual MOL_User MOL_User { get; set; }
        public virtual MOL_User MOL_User1 { get; set; }
        public virtual ICollection<MOL_EstablishmentVisaCreditJobsHistory> MOL_EstablishmentVisaCreditJobsHistory { get; set; }
    }
}
