//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{

    public partial class MOL_GC_AssentJobs
    {
        public int ID { get; set; }
        public int AssentID { get; set; }
        public int JobID { get; set; }
        public int RequiredNumber { get; set; }
        public int GenderID { get; set; }
    
        public virtual Enum_Gender Enum_Gender { get; set; }
        public virtual Lookup_Job Lookup_Job { get; set; }
        public virtual MOL_GC_Assents MOL_GC_Assents { get; set; }
    }
}
