//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;

    public partial class MOL_EstablishmentVisaCreditJobsHistory
    {
        public int ID { get; set; }
        public int ConsumerID { get; set; }
        public Nullable<int> OperationVisaCreditID { get; set; }
        public int VisaCreditJobID { get; set; }
        public int JobID { get; set; }
        public int GenderID { get; set; }
        public int ApprovedCredit { get; set; }
        public int UsedCredit { get; set; }
        public int AvailableCredit { get; set; }
        public int OperationTypeID { get; set; }
        public int OperationValue { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid TransactionLogID { get; set; }
        public virtual Enum_EstablishmentVisaCreditJobOperationType Enum_EstablishmentVisaCreditJobOperationType { get; set; }
        public virtual Enum_Gender Enum_Gender { get; set; }
        public virtual Lookup_EstablishmentVisaCreditServiceConsumers Lookup_EstablishmentVisaCreditServiceConsumers { get; set; }
        public virtual Lookup_Job Lookup_Job { get; set; }
        public virtual MOL_EstablishmentVisaCreditJobs MOL_EstablishmentVisaCreditJobs { get; set; }
        public virtual MOL_User MOL_User { get; set; }
    }
}
