//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;

    public partial class MOL_GC_ContractEstablishments
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public long EstablishmentID { get; set; }
        public Nullable<int> IssuedCredit { get; set; }
    
        public virtual MOL_Establishment MOL_Establishment { get; set; }
        public virtual MOL_GC_Contracts MOL_GC_Contracts { get; set; }
    }
}
