//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MOL_GC_Contracts
    {
        public MOL_GC_Contracts()
        {
            this.MOL_GC_Contracts1 = new HashSet<MOL_GC_Contracts>();
            this.MOL_GC_Contracts11 = new HashSet<MOL_GC_Contracts>();
            this.MOL_GC_ContractEstablishments = new HashSet<MOL_GC_ContractEstablishments>();
        }
    
        public int ID { get; set; }
        public long GovEntityID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public int FieldID { get; set; }
        public bool IsReplacementContract { get; set; }
        public Nullable<int> ReplacementContractID { get; set; }
        public string Number { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<long> LastModifiedBy { get; set; }
        public Nullable<int> EndReasonID { get; set; }
        public Nullable<int> ReplacedByContractID { get; set; }
        public Nullable<long> ApprovalDoneBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalComment { get; set; }
        public Nullable<System.Guid> VisaCreditDBGroupingReference { get; set; }
    
        public virtual Lookup_GC_ContractFields Lookup_GC_ContractFields { get; set; }
        public virtual ICollection<MOL_GC_Contracts> MOL_GC_Contracts1 { get; set; }
        public virtual MOL_GC_Contracts MOL_GC_Contracts2 { get; set; }
        public virtual ICollection<MOL_GC_Contracts> MOL_GC_Contracts11 { get; set; }
        public virtual MOL_GC_Contracts MOL_GC_Contracts3 { get; set; }
        public virtual MOL_User MOL_User { get; set; }
        public virtual MOL_User MOL_User1 { get; set; }
        public virtual MOL_User MOL_User2 { get; set; }
        public virtual ICollection<MOL_GC_ContractEstablishments> MOL_GC_ContractEstablishments { get; set; }
        public virtual Channels Channels { get; set; }
    }
}
