//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;

    public partial class MOL_GC_AssentTrackingLog
    {
        public long ID { get; set; }
        public int AssentID { get; set; }
        public int AssentStatusID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long UserID { get; set; }
        public Nullable<int> AssentEditReasonID { get; set; }
        public string RejectReason { get; set; }
    
        public virtual MOL_GC_Assents MOL_GC_Assents { get; set; }
        public virtual MOL_User MOL_User { get; set; }
    }
}
