//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;

    public partial class Mol_VwLaborersHasUnusedWP
    {
        public long PK_LaborerId { get; set; }
        public int FK_LaborOfficeId { get; set; }
        public int FK_SaudiFlagId { get; set; }
        public long SequenceNumber { get; set; }
        public string IdNo { get; set; }
        public string BorderNo { get; set; }
        public Nullable<System.DateTime> LastWPExpirationDate { get; set; }
        public Nullable<System.DateTime> KingdomEntryDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    }
}
