//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MOL_GC_Assents
    {
        public MOL_GC_Assents()
        {
            this.MOL_GC_AssentJobs = new HashSet<MOL_GC_AssentJobs>();
            this.MOL_GC_AssentTrackingLog = new HashSet<MOL_GC_AssentTrackingLog>();
        }
    
        public int ID { get; set; }
        public long GovEntityID { get; set; }
        public int StatusID { get; set; }
        public string Number { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long EstablishmentID { get; set; }
        public Nullable<int> IssuedCredit { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<long> LastModifiedBy { get; set; }
        public Nullable<int> EndReasonID { get; set; }
        public Nullable<long> ApprovalDoneBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalComment { get; set; }
        public Nullable<System.Guid> VisaCreditDBGroupingReference { get; set; }
        public bool IsFinancialNitaqat { get; set; }
    
        //public virtual MOL_Establishment MOL_Establishment { get; set; }
        //public virtual MOL_User MOL_User { get; set; }
        //public virtual MOL_User MOL_User1 { get; set; }
        //public virtual MOL_User MOL_User2 { get; set; }
        public virtual ICollection<MOL_GC_AssentJobs> MOL_GC_AssentJobs { get; set; }
        public virtual ICollection<MOL_GC_AssentTrackingLog> MOL_GC_AssentTrackingLog { get; set; }
        public virtual Channels Channels { get; set; }
    }
}
