//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{

    public partial class MOL_EconomicActivity_Jobs_Gender
    {
        public int FK_EconomicActivityID { get; set; }
        public int FK_JobID { get; set; }
        public bool IsGenderRequired { get; set; }
    
        public virtual Lookup_EconomicActivity Lookup_EconomicActivity { get; set; }
        public virtual Lookup_Job Lookup_Job { get; set; }
    }
}
