//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System;

    public partial class MOL_EstablishmentModifiedJobsHistory
    {
        public int Id { get; set; }
        public long CreditId { get; set; }
        public int OldJobId { get; set; }
        public int NewJobId { get; set; }
        public Nullable<int> OldGenderId { get; set; }
        public Nullable<int> NewGenderId { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
