//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOL.EFDAL.Models
{
    using System.Collections.Generic;

    public partial class RejectionReason
    {
        public RejectionReason()
        {
            this.IstikdamRequestRejectionReasons = new HashSet<IstikdamRequestRejectionReason>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<IstikdamRequestRejectionReason> IstikdamRequestRejectionReasons { get; set; }
    }
}
