//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMS.ApplicationServices.ExReferenceSMSService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsType", Namespace="http://mol.gov.sa/services/")]
    public enum SmsType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTP = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mol.gov.sa/services/", ConfigurationName="ExReferenceSMSService.INotificationService")]
    public interface INotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mol.gov.sa/services/INotificationService/SendSms", ReplyAction="http://mol.gov.sa/services/INotificationService/SendSmsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mol.Integration.ServiceWrapper.NoteService.NoteServiceReference.FaultContract), Action="http://mol.gov.sa/services/INotificationService/SendSmsFaultContractFault", Name="FaultContract")]
        bool SendSms(string mobileNumber, string smsText, RAMS.ApplicationServices.ExReferenceSMSService.SmsType smsType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mol.gov.sa/services/INotificationService/SendSms", ReplyAction="http://mol.gov.sa/services/INotificationService/SendSmsResponse")]
        System.Threading.Tasks.Task<bool> SendSmsAsync(string mobileNumber, string smsText, RAMS.ApplicationServices.ExReferenceSMSService.SmsType smsType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationServiceChannel : RAMS.ApplicationServices.ExReferenceSMSService.INotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationServiceClient : System.ServiceModel.ClientBase<RAMS.ApplicationServices.ExReferenceSMSService.INotificationService>, RAMS.ApplicationServices.ExReferenceSMSService.INotificationService {
        
        public NotificationServiceClient() {
        }
        
        public NotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendSms(string mobileNumber, string smsText, RAMS.ApplicationServices.ExReferenceSMSService.SmsType smsType) {
            return base.Channel.SendSms(mobileNumber, smsText, smsType);
        }
        
        public System.Threading.Tasks.Task<bool> SendSmsAsync(string mobileNumber, string smsText, RAMS.ApplicationServices.ExReferenceSMSService.SmsType smsType) {
            return base.Channel.SendSmsAsync(mobileNumber, smsText, smsType);
        }
    }
}
